from quantsuite.amfe import AMFE
from quantsuite.data_manipulator import DataManipulator
from quantsuite.pairs_trading import PairsTrading
from quantsuite.performance_evaluation import PerformanceEvaluation
from quantsuite.portfolio_analysis import PortfolioAnalysis
from quantsuite.researcher import EAPResearcher
from quantsuite.transformers import Winsorizer, Identity
